require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/**/*
    - Gemfile

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  
Style/Documentation:
    Enabled: false